name: Component tests
on:
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          build: npm run build
          start: npm run start
          browser: chrome
          component: true
